### ISSUE TITLE
on what computer were you able to see the cameras wifi

### ISSUE THREAD

**Issue by vmoldo** [vitorio/gear360-2017-mods#1]
i've tried to connect to this cameras wifi from several devices and it only seems to work from samsung phones and iphone, all my other devices (pc, phones, tablets, router) don't even show the ssid of this camera in the list

**Comment by vitorio** [comment]
@vmoldo I usually trigger it from my Android phone (non-Samsung), but I just tried it following the steps in the readme, and I can see it from my Android phone, my MacBook Air, and my Windows desktop PC:

- I turn my camera on.  This is for the Gear 360 (2017) model, the tall one, if you have the 2016 ball, can't help you.
- I held down "Menu" until it prompted me with one of the "Connect to" options.  I picked "Connect to iOS".
- I could see the advertised access point SSID on my phone, on my MacBook Air, and on my Windows PC.

Only other thing I can think of, is make sure you're using the latest firmware, R210GLU0ARB2.  You won't have the "Connect to Street View" option otherwise, but maybe they did other things to the wifi as well?

**Comment by vmoldo** [comment]
i used to be able to use it with my LG phone before Android 8 too via wifi direct with the modded app from xda. but i was never able to see the SSID on anything that's not an iPhone or a Samsung phone. I'm starting to wonder if my device is faulty after reading your responses tho 

i have the di*k shape 2017 model

**Comment by vitorio** [comment]
Sorry to hear that! Again, make sure you have the latest firmware, and try connecting to the other access point options (Connect to iOS, Connect to Android, Connect to Street View).  Good luck!
